local l = LOCALIZE.ru

l.donat_mission_day1 = "Выполни все ежедневные задания!"
l.donat_mission_day2 = "Снайпер"
l.donat_mission_day2_desc = "Убей трёх игроков в голову"
l.donat_mission_day3 = "Суицыд"
l.donat_mission_day3_desc = "Сделай суицыд при помощи огнестрельного оружия"
l.donat_mission_day4 = "Смертник"
l.donat_mission_day4_desc = "Умри 10 раз"
l.donat_mission_day5 = "Выиграй Team Death Match"
l.donat_mission_day6 = "Выиграй Homicide"
l.donat_mission_day7 = "Выиграй за трейтора"
l.donat_mission_day7_desc = "Я предатель!"
l.donat_mission_day8 = "Съешь полностью любую еду"
l.donat_mission_day8_desc = "Я поел"
l.donat_mission_day9 = "Дзюдоист"
l.donat_mission_day9_desc = "Убей 3 игроков ближнем оружием (топором, битой, ножом)"
l.donat_mission_day10 = "Подрывник"
l.donat_mission_day10_desc = "Убейте игрока при помощи бомбы от трейтора"
l.donat_mission_day11 = "Яд"
l.donat_mission_day11_desc = "Убей одного игрока при помощи яда за трейтора"
l.donat_mission_day12 = "МЕДИК!"
l.donat_mission_day12_desc = "Полечите кого-нибудь медикаментами"

